namespace BuilderTests
{
    using InnoSetup.ScriptBuilder;

    public class TestBuilder : IssBuilder
    {
        public TestBuilder()
        {
            Setup.Create("BimTools.Support")
                .AppVersion("1.2.5.1634640046")
                .DefaultDirName(@"{userappdata}\Autodesk\Revit\Addins\2019\SupportTools")
                .PrivilegesRequired(PrivilegesRequired.Lowest)
                .OutputBaseFilename("BimTools.Support_2021_1.2.5.1634640046")
                .SetupIconFile("trayIcon.ico")
                .UninstallDisplayIcon("trayIcon.ico")
                .DisableDirPage(YesNo.Yes)
                
                        
.AppVerName("AppVerName")
.AppId("AppId")
.AppCopyright("AppCopyright")
.AppPublisher("AppPublisher")
.AppPublisherURL("AppPublisherURL")
.AppSupportPhone("AppSupportPhone")
.AppSupportURL("AppSupportURL")
.AppUpdatesURL("AppUpdatesURL")
.DefaultGroupName("DefaultGroupName")
.BaseFilename("BaseFilename")
.UninstallFilesDir("UninstallFilesDir")
.UninstallDisplayName("UninstallDisplayName")
.AppMutex("AppMutex")
.DefaultUserInfoName("DefaultUserInfoName")
.DefaultUserInfoOrg("DefaultUserInfoOrg")
.DefaultUserInfoSerial("DefaultUserInfoSerial")
.AppReadmeFile("AppReadmeFile")
.AppContact("AppContact")
.AppComments("AppComments")
.AppModifyPath("AppModifyPath")
.CreateUninstallRegKey("CreateUninstallRegKey")
.Uninstallable(YesNo.Yes)
.CloseApplicationsFilter("CloseApplicationsFilter")
.SetupMutex("SetupMutex")
.ChangesEnvironment(YesNo.Yes)
.ChangesAssociations(YesNo.Yes)
.InfoBeforeText("InfoBeforeText")
.LicenseText("LicenseText")
.LicenseFile("LicenseFile")
.InfoAfterText("InfoAfterText")
.CompiledCodeText("CompiledCodeText")
.NumLanguageEntries(1)
.NumCustomMessageEntries(2)
.NumPermissionEntries(3)
.NumTypeEntries(4)
.NumComponentEntries(5)
.NumTaskEntries(6)
.NumDirEntries(7)
.NumFileEntries(8)
.NumFileLocationEntries(9)
.NumIconEntries(10)
.NumIniEntries(11)
.NumRegistryEntries(12)
.NumInstallDeleteEntries(13)
.NumUninstallDeleteEntries(14)
.NumRunEntries(15)
.NumUninstallRunEntries(16)
.BackColor(17)
.BackColor2(17)
.DirExistsWarning(YesNo.Yes)
.ShowLanguageDialog(YesNo.Yes)
.UninstallLogMode(UninstallLogMode.Overwrite)
.WizardImageAlphaFormat(WizardImageAlphaFormat.Premultiplied)
.WizardSizePercentX(19)
.WizardSizePercentY(20)
.ExtraDiskSpaceRequired(21)
.SlicesPerDisk(22)
.UninstallDisplaySize(23)
.DisableProgramGroupPage(YesNo.Yes)
.DisableWelcomePage(YesNo.Yes)
.PrivilegesRequiredOverridesAllowed(SetupPrivilegesRequiredOverrides.CommandLine)
.Options(SetupOption.SignedUninstaller)
.OutputDir("OutputDir")
.OutputManifestFile("OutputManifestFile")
.WizardImageFile("WizardImageFile")
.WizardSmallImageFile("WizardSmallImageFile")
.AllowCancelDuringInstall(YesNo.Yes)
.AllowNetworkDrive(YesNo.Yes)
.AllowNoIcons(YesNo.Yes)
.AllowRootDirectory(YesNo.Yes)
.AllowUNCPath(YesNo.Yes)
.AlwaysRestart(YesNo.Yes)
.AlwaysShowComponentsList(YesNo.Yes)
.AlwaysShowDirOnReadyPage(YesNo.Yes)
.AlwaysShowGroupOnReadyPage(YesNo.Yes)
.AlwaysUsePersonalGroup(YesNo.Yes)
.AppendDefaultDirName(YesNo.Yes)
.AppendDefaultGroupName(YesNo.Yes)
.ArchitecturesAllowed(Architectures.X86)
.ArchitecturesInstallIn64BitMode(ArchitecturesInstallIn64BitMode.Arm64)
.ASLRCompatible(YesNo.Yes)
.BackColorDirection(BackColorDirection.TopToBottom)
.BackSolid(YesNo.Yes)
.CloseApplications(CloseApplications.Force)
.Compression("Compression")
.CompressionThreads(24)
.CreateAppDir(YesNo.Yes)
.DefaultDialogFontName("DefaultDialogFontName")
.DEPCompatible(YesNo.Yes)
.DisableFinishedPage(YesNo.Yes)
.DisableReadyMemo(YesNo.Yes)
.DisableReadyPage(YesNo.Yes)
.DisableStartupPrompt(YesNo.Yes)
.DiskClusterSize(25)
.DiskSliceSize(26)
.DiskSpanning(YesNo.Yes)
.EnableDirDoesntExistWarning(YesNo.Yes)
.Encryption(YesNo.Yes)
.FlatComponentsList(YesNo.Yes)
.InfoAfterFile("InfoAfterFile")
.InfoBeforeFile("InfoBeforeFile")
.InternalCompressLevel("InternalCompressLevel")
.LanguageDetectionMethod(LanguageDetectionMethod.Locale)
.LZMAAlgorithm(27)
.LZMABlockSize(28)
.LZMADictionarySize(29)
.LZMAMatchFinder(LzmaMatchFinder.Hc)
.LZMANumBlockThreads(30)
.LZMANumFastBytes(31)
.LZMAUseSeparateProcess(YesNo.Yes)
.MergeDuplicateFiles(YesNo.Yes)
.MinVersion("MinVersion")
.MissingMessagesWarning(YesNo.Yes)
.MissingRunOnceIdsWarning(YesNo.Yes)
.NotRecognizedMessagesWarning(YesNo.Yes)
.OnlyBelowVersion("OnlyBelowVersion")
.Output(YesNo.Yes)
.Password("Password")
.ReserveBytes(32)
.RestartApplications(YesNo.Yes)
.RestartIfNeededByRun(YesNo.Yes)
.SetupLogging(YesNo.Yes)
.ShowComponentSizes(YesNo.Yes)
.ShowTasksTreeLines(YesNo.Yes)
.ShowUndisplayableLanguages(YesNo.Yes)
.SignedUninstaller(YesNo.Yes)
.SignedUninstallerDir("SignedUninstallerDir")
.SignTool("SignTool")
.SignToolMinimumTimeBetween(33)
.SignToolRetryCount(34)
.SignToolRetryDelay(35)
.SignToolRunMinimized(YesNo.Yes)
.SolidCompression(YesNo.Yes)
.SourceDir("SourceDir")
.TerminalServicesAware(YesNo.Yes)
.TimeStampRounding(36)
.TimeStampsInUTC(YesNo.Yes)
.TouchDate("TouchDate")
.TouchTime("TouchTime")
.UpdateUninstallLogAppName(YesNo.Yes)
.UninstallRestartComputer(YesNo.Yes)
.UsedUserAreasWarning(YesNo.Yes)
.UsePreviousAppDir(YesNo.Yes)
.UsePreviousGroup(YesNo.Yes)
.UsePreviousLanguage(YesNo.Yes)
.UsePreviousPrivileges(YesNo.Yes)
.UsePreviousSetupType(YesNo.Yes)
.UsePreviousTasks(YesNo.Yes)
.UsePreviousUserInfo(YesNo.Yes)
.UseSetupLdr(YesNo.Yes)
.UserInfoPage(YesNo.Yes)
.VersionInfoCompany("VersionInfoCompany")
.VersionInfoCopyright("VersionInfoCopyright")
.VersionInfoDescription("VersionInfoDescription")
.VersionInfoOriginalFileName("VersionInfoOriginalFileName")
.VersionInfoProductName("VersionInfoProductName")
.VersionInfoProductVersion("VersionInfoProductVersion")
.VersionInfoProductTextVersion("VersionInfoProductTextVersion")
.VersionInfoTextVersion("VersionInfoTextVersion")
.VersionInfoVersion("VersionInfoVersion")
.WindowResizable(YesNo.Yes)
.WindowShowCaption(YesNo.Yes)
.WindowStartMaximized(YesNo.Yes)
.WindowVisible(YesNo.Yes)
.WizardImageStretch(YesNo.Yes)
.WizardResizable(YesNo.Yes)
.WizardSizePercent("WizardSizePercent")
.WizardStyle(WizardStyle.Modern);

            Files.CreateEntry("Source", "DestDir")
                .DestName("DestName")
                .Attribs(AttribsFlags.System | AttribsFlags.Readonly)
                .FontInstall("FontInstall")
                .Excludes("Excludes")
                .ExternalSize(123456)
                .StrongAssemblyName("StrongAssemblyName")
                .Flags(FileFlags.Sign | FileFlags.Sign)
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .AddPermission(Sids.Service, Permissions.Full)
                .AddPermission(Sids.Admins, Permissions.Modify)
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            Files.CreateEntry(source: "SupportTools.addin", destDir: @"{userappdata}\Autodesk\Revit\Addins\2019");

            Components
                .CreateEntry("Name", "Description")
                .Types("Types")
                .ExtraDiskSpaceRequired(123456)
                .Flags(ComponentFlags.Fixed | ComponentFlags.Exclusive)
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check");
            Components.CreateEntry("main", "Main Files");

            Tasks.CreateEntry("Name", "Description")
                .Components("Components")
                .GroupDescription("GroupDescription")
                .Flags(TaskFlags.CheckedOnce | TaskFlags.Restart)
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check");
            Tasks.CreateEntry("Name", "Description");

            Types
                .CreateEntry("Name", "Description")
                .Flags(TypeFlags.IsCustom)
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check");
            Types.CreateEntry("Name", "Description");

            Dirs.CreateEntry("Name")
                .Attribs(AttribsFlags.System | AttribsFlags.Hidden)
                .Flags(DirFlags.UninsAlwaysUninstall)
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .AddPermission(Sids.Service, Permissions.Full)
                .AddPermission(Sids.Admins, Permissions.Modify)
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            Dirs.CreateEntry("Name");
            
            Icons.CreateEntry("Name", "Filename")
                .Parameters("Parameters")
                .WorkingDir("WorkingDir")
                .Comment("Comment")
                .HotKey("HotKey")
                .IconFilename("IconFilename")
                .IconIndex(11)
                .AppUserModelID("AppUserModelID")
                .AppUserModelToastActivatorCLSID("AppUserModelToastActivatorCLSID")
                .Flags(IconFlags.UninsNeverUninstall | IconFlags.CloseOnExit)
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            Icons.CreateEntry("Name", "Filename");

            Languages.CreateEntry("Name", "MessagesFile")
                .LicenseFile("LicenseFile")
                .InfoAfterFile("InfoAfterFile")
                .InfoBeforeFile("InfoBeforeFile")
                .Check("Check");
            Languages.CreateEntry("Name", "MessageFile");

            LangOptions.Create()
                .LanguageName("LanguageName")
                .DialogFontName("DialogFontName")
                .DialogFontSize(1)
                .WelcomeFontName("WelcomeFontName")
                .WelcomeFontSize(2)
                .TitleFontName("TitleFontName")
                .TitleFontSize(3)
                .CopyrightFontName("CopyrightFontName")
                .CopyrightFontSize(4)
                .RightToLeft(YesNo.Yes)
                .LanguageID("en-us")
                .LanguageCodePage(1111);

            INI.CreateEntry("Filename", "Section")
                .String("String")
                .Key("Key")
                .Flags(IniFlags.UninsDeleteEntry | IniFlags.CreateKeyIfDoesntExist)
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            INI.CreateEntry("Filename", "Section");

            Registry.CreateEntry(RegistryKeys.HKCU, "Subkey")
                .ValueName("ValueName")
                .ValueType(ValueTypes.String)
                .ValueData("ValueData")
                .Flags(RegistryFlags.CreateValueIfDoesntExist | RegistryFlags.NoError)
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .AddPermission(Sids.Service, Permissions.Full)
                .AddPermission(Sids.Admins, Permissions.Modify)
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            Registry.CreateEntry(RegistryKeys.HKU, @"Software\My Company\My Program");
            Run.CreateEntry("FileName")
                .Description("Description")
                .WorkingDir("WorkingDir")
                .StatusMsg("StatusMsg")
                .RunOnceId("RunOnceId")
                .Parameters("Parameters")
                .Verb("Verb")
                .Flags(RunFlags._64bit | RunFlags.RunHidden)
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            Run.CreateEntry("FileName");
            
            UninstallRun.CreateEntry("FileName");
            
            UninstallDelete.CreateEntry(DeleteTypes.Files,"Name")
                .Components("Components")
                .Tasks("Tasks")
                .Languages("Languages")
                .MinVersion("MinVersion")
                .OnlyBelowVersion("OnlyBelowVersion")
                .Check("Check")
                .BeforeInstall("BeforeInstall")
                .AfterInstall("AfterInstall");
            UninstallDelete.CreateEntry(DeleteTypes.Files,"Name");
            InstallDelete.CreateEntry(DeleteTypes.Files,"Name");

            Messages.CreateEntry()
                .Parameter("NextButton", "&Forward");
            
            CustomMessages.CreateEntry()
                .Parameter("NextButton", "&Forward");

            Sections.CreateParameterSection("UnimplementedParameterSection")
                .CreateEntry()
                .Parameter("Root", RegistryKeys.HKU)
                .Parameter("Subkey", @"Software\My Company\My Program")
                .Parameter("ValueName", "Name")
                .Parameter("ValueType", ValueTypes.String)
                .Parameter("ValueData", "Test app");

            Sections.CreateKeyValueSection("UnimplementedKeyValueSection")
                .CreateEntry()
                .Parameter("BeveledLabel", @"Inno Setup")
                .Parameter("HelpTextNote", @"/PORTABLE=1%nEnable portable mode.");

            Code.CreateEntry("script");
        }
    }
}