namespace InnoSetup.ScriptBuilder
{
    using System;

    [Flags]
    public enum FileFlags : ulong
    {
        _32bit = 1ul,
        _64bit = 1ul << 1,
        AllowUnsafeFiles = 1ul << 2,
        CompareTimestamp = 1ul << 3,
        ConfirmOverwrite = 1ul << 4,
        CreateAllSubdirs = 1ul << 5,
        DeleteAfterInstall = 1ul << 6,
        DontCopy = 1ul << 7,
        DontVerifyChecksum = 1ul << 8,
        External = 1ul << 9,
        FontIsntTrueType = 1ul << 10,
        GacInstall = 1ul << 11,
        IgnoreVersion = 1ul << 12,
        IsReadme = 1ul << 13,
        NoCompression = 1ul << 14,
        NoEncryption = 1ul << 15,
        NoRegError = 1ul << 16,
        OnlyIfDestFileExists = 1ul << 17,
        OnlyIfDoesntExist = 1ul << 18,
        OverwriteReadonly = 1ul << 19,
        PromptIfolder = 1ul << 20,
        RecurseSubdirs = 1ul << 21,
        RegServer = 1ul << 22,
        RegTypeLib = 1ul << 23,
        ReplaceSameVersion = 1ul << 24,
        RestartReplace = 1ul << 25,
        SetNtfsCompression = 1ul << 26,
        SharedFile = 1ul << 27,
        Sign = 1ul << 28,
        SignCheck = 1ul << 29,
        SignOnce = 1ul << 30,
        SkipIfSourceDoesntExist = 1ul << 31,
        SolidBreak = 1ul << 32,
        SortFilesByExtension = 1ul << 33,
        SortFilesByName = 1ul << 34,
        Touch = 1ul << 35,
        UninsNoSharedFilePrompt = 1ul << 36,
        UninsRemoveReadonly = 1ul << 37,
        UninsRestartDelete = 1ul << 38,
        UninsNeverUninstall = 1ul << 39,
        UnsetNtfsCompression = 1ul << 40,
     }
}